### ISSUE TITLE
[Money Forward Vietnam] - Senior Golang Engineer - URGENT

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2547] opened 2021-06-11 02:46 UTC
## Location
* Etown Doan Van Bo, District 4, Vietnam (near D1)

## Salary Expectation
* We offer salary based on your expectation

### Must Have
* 3+ years of Golang experience 
* Experience in reviewing code
* Experience in writing good unit tests

### Ideally
* Experience with frontend development (ReactJS, VueJS, jQuery)

### Responsibilities
* Develop and design service
* Design database schema
* Write clean and maintainable code
* Discuss and debate with other team members to find optimal solutions

### What we expect?
Teamwork, Fun, Speed, Pride, Respect.

### Why it would be awesome to work with us?
* TOP 1 Fintech company in Japan
* Interesting & challenging project
* English speaking environment
* Full pay probation
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: Additional 3-day vacation (15 days in total), Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary)
* Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7)
* Health care: Annual health check
* Training:
1. External or internal training courses
2. Internal workshop
3. Support Attending Conference
4. Scrum training
5. Order books based on member's requests

* Others:
1. Grab expenses on the party day
2. Club activities, playstation, billiard, etc…
3. Free bike parking, fruits and coffee

### Contact
Mail: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009
Mobile: 0906 516 291

**Comment by qcam** [comment] 2021-09-15 07:56
duplicate of https://github.com/awesome-jobs/vietnam/issues/2789

**Closed as completed by qcam** 2021-09-15 07:56 UTC
